// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: conversations.sql

package sqlitedb

import (
	"context"
	"database/sql"
)

const createConversation = `-- name: CreateConversation :exec
INSERT INTO conversations (id, model, title, system_prompt, message_count, created_at, updated_at, metadata)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateConversationParams struct {
	ID           string         `json:"id"`
	Model        string         `json:"model"`
	Title        sql.NullString `json:"title"`
	SystemPrompt sql.NullString `json:"system_prompt"`
	MessageCount sql.NullInt64  `json:"message_count"`
	CreatedAt    int64          `json:"created_at"`
	UpdatedAt    int64          `json:"updated_at"`
	Metadata     sql.NullString `json:"metadata"`
}

func (q *Queries) CreateConversation(ctx context.Context, arg CreateConversationParams) error {
	_, err := q.db.ExecContext(ctx, createConversation,
		arg.ID,
		arg.Model,
		arg.Title,
		arg.SystemPrompt,
		arg.MessageCount,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Metadata,
	)
	return err
}

const deleteConversation = `-- name: DeleteConversation :exec
DELETE FROM conversations WHERE id = ?
`

func (q *Queries) DeleteConversation(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteConversation, id)
	return err
}

const getConversation = `-- name: GetConversation :one
SELECT id, model, title, system_prompt, message_count, created_at, updated_at, metadata
FROM conversations WHERE id = ?
`

func (q *Queries) GetConversation(ctx context.Context, id string) (Conversation, error) {
	row := q.db.QueryRowContext(ctx, getConversation, id)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.Model,
		&i.Title,
		&i.SystemPrompt,
		&i.MessageCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Metadata,
	)
	return i, err
}

const incrementMessageCount = `-- name: IncrementMessageCount :exec
UPDATE conversations SET message_count = message_count + 1, updated_at = ? WHERE id = ?
`

type IncrementMessageCountParams struct {
	UpdatedAt int64  `json:"updated_at"`
	ID        string `json:"id"`
}

func (q *Queries) IncrementMessageCount(ctx context.Context, arg IncrementMessageCountParams) error {
	_, err := q.db.ExecContext(ctx, incrementMessageCount, arg.UpdatedAt, arg.ID)
	return err
}

const listConversations = `-- name: ListConversations :many
SELECT id, model, title, system_prompt, message_count, created_at, updated_at, metadata
FROM conversations ORDER BY updated_at DESC LIMIT ? OFFSET ?
`

type ListConversationsParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListConversations(ctx context.Context, arg ListConversationsParams) ([]Conversation, error) {
	rows, err := q.db.QueryContext(ctx, listConversations, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Conversation{}
	for rows.Next() {
		var i Conversation
		if err := rows.Scan(
			&i.ID,
			&i.Model,
			&i.Title,
			&i.SystemPrompt,
			&i.MessageCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resetMessageCount = `-- name: ResetMessageCount :exec
UPDATE conversations SET message_count = 0, updated_at = ? WHERE id = ?
`

type ResetMessageCountParams struct {
	UpdatedAt int64  `json:"updated_at"`
	ID        string `json:"id"`
}

func (q *Queries) ResetMessageCount(ctx context.Context, arg ResetMessageCountParams) error {
	_, err := q.db.ExecContext(ctx, resetMessageCount, arg.UpdatedAt, arg.ID)
	return err
}

const updateConversation = `-- name: UpdateConversation :exec
UPDATE conversations
SET model = ?, title = ?, system_prompt = ?, message_count = ?, updated_at = ?, metadata = ?
WHERE id = ?
`

type UpdateConversationParams struct {
	Model        string         `json:"model"`
	Title        sql.NullString `json:"title"`
	SystemPrompt sql.NullString `json:"system_prompt"`
	MessageCount sql.NullInt64  `json:"message_count"`
	UpdatedAt    int64          `json:"updated_at"`
	Metadata     sql.NullString `json:"metadata"`
	ID           string         `json:"id"`
}

func (q *Queries) UpdateConversation(ctx context.Context, arg UpdateConversationParams) error {
	_, err := q.db.ExecContext(ctx, updateConversation,
		arg.Model,
		arg.Title,
		arg.SystemPrompt,
		arg.MessageCount,
		arg.UpdatedAt,
		arg.Metadata,
		arg.ID,
	)
	return err
}
