// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: launch_profiles.sql

package sqlitedb

import (
	"context"
	"database/sql"
)

const createLaunchProfile = `-- name: CreateLaunchProfile :exec
INSERT INTO launch_profiles (id, name, backend_type, installation_id, model_scope, params, env, extra_args, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateLaunchProfileParams struct {
	ID             string         `json:"id"`
	Name           string         `json:"name"`
	BackendType    string         `json:"backend_type"`
	InstallationID sql.NullString `json:"installation_id"`
	ModelScope     sql.NullString `json:"model_scope"`
	Params         string         `json:"params"`
	Env            sql.NullString `json:"env"`
	ExtraArgs      sql.NullString `json:"extra_args"`
	CreatedAt      int64          `json:"created_at"`
	UpdatedAt      int64          `json:"updated_at"`
}

func (q *Queries) CreateLaunchProfile(ctx context.Context, arg CreateLaunchProfileParams) error {
	_, err := q.db.ExecContext(ctx, createLaunchProfile,
		arg.ID,
		arg.Name,
		arg.BackendType,
		arg.InstallationID,
		arg.ModelScope,
		arg.Params,
		arg.Env,
		arg.ExtraArgs,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteLaunchProfile = `-- name: DeleteLaunchProfile :exec
DELETE FROM launch_profiles WHERE id = ?
`

func (q *Queries) DeleteLaunchProfile(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteLaunchProfile, id)
	return err
}

const getLaunchProfile = `-- name: GetLaunchProfile :one
SELECT id, name, backend_type, installation_id, model_scope, params, env, extra_args, created_at, updated_at
FROM launch_profiles WHERE id = ?
`

func (q *Queries) GetLaunchProfile(ctx context.Context, id string) (LaunchProfile, error) {
	row := q.db.QueryRowContext(ctx, getLaunchProfile, id)
	var i LaunchProfile
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BackendType,
		&i.InstallationID,
		&i.ModelScope,
		&i.Params,
		&i.Env,
		&i.ExtraArgs,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listLaunchProfiles = `-- name: ListLaunchProfiles :many
SELECT id, name, backend_type, installation_id, model_scope, params, env, extra_args, created_at, updated_at
FROM launch_profiles
WHERE (?1 = '' OR backend_type = ?1)
  AND (?2 = '' OR model_scope = '' OR model_scope = ?2)
ORDER BY name ASC
`

type ListLaunchProfilesParams struct {
	BackendTypeFilter interface{} `json:"backend_type_filter"`
	ModelScopeFilter  interface{} `json:"model_scope_filter"`
}

func (q *Queries) ListLaunchProfiles(ctx context.Context, arg ListLaunchProfilesParams) ([]LaunchProfile, error) {
	rows, err := q.db.QueryContext(ctx, listLaunchProfiles, arg.BackendTypeFilter, arg.ModelScopeFilter)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LaunchProfile{}
	for rows.Next() {
		var i LaunchProfile
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.BackendType,
			&i.InstallationID,
			&i.ModelScope,
			&i.Params,
			&i.Env,
			&i.ExtraArgs,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLaunchProfile = `-- name: UpdateLaunchProfile :exec
UPDATE launch_profiles
SET name = ?, backend_type = ?, installation_id = ?, model_scope = ?, params = ?, env = ?, extra_args = ?, updated_at = ?
WHERE id = ?
`

type UpdateLaunchProfileParams struct {
	Name           string         `json:"name"`
	BackendType    string         `json:"backend_type"`
	InstallationID sql.NullString `json:"installation_id"`
	ModelScope     sql.NullString `json:"model_scope"`
	Params         string         `json:"params"`
	Env            sql.NullString `json:"env"`
	ExtraArgs      sql.NullString `json:"extra_args"`
	UpdatedAt      int64          `json:"updated_at"`
	ID             string         `json:"id"`
}

func (q *Queries) UpdateLaunchProfile(ctx context.Context, arg UpdateLaunchProfileParams) error {
	_, err := q.db.ExecContext(ctx, updateLaunchProfile,
		arg.Name,
		arg.BackendType,
		arg.InstallationID,
		arg.ModelScope,
		arg.Params,
		arg.Env,
		arg.ExtraArgs,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
