// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: model_metadata.sql

package sqlitedb

import (
	"context"
	"database/sql"
)

const deleteModelMetadata = `-- name: DeleteModelMetadata :exec
DELETE FROM model_metadata WHERE model_id = ?
`

func (q *Queries) DeleteModelMetadata(ctx context.Context, modelID string) error {
	_, err := q.db.ExecContext(ctx, deleteModelMetadata, modelID)
	return err
}

const getAllModelMetadata = `-- name: GetAllModelMetadata :many
SELECT model_id, node_id, storage_path, alias, favourite, tags, description,
       load_count, last_loaded, total_tokens, capabilities, created_at, updated_at
FROM model_metadata
`

func (q *Queries) GetAllModelMetadata(ctx context.Context) ([]ModelMetadatum, error) {
	rows, err := q.db.QueryContext(ctx, getAllModelMetadata)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ModelMetadatum{}
	for rows.Next() {
		var i ModelMetadatum
		if err := rows.Scan(
			&i.ModelID,
			&i.NodeID,
			&i.StoragePath,
			&i.Alias,
			&i.Favourite,
			&i.Tags,
			&i.Description,
			&i.LoadCount,
			&i.LastLoaded,
			&i.TotalTokens,
			&i.Capabilities,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getModelMetadata = `-- name: GetModelMetadata :one
SELECT model_id, node_id, storage_path, alias, favourite, tags, description,
       load_count, last_loaded, total_tokens, capabilities, created_at, updated_at
FROM model_metadata
WHERE model_id = ?
`

func (q *Queries) GetModelMetadata(ctx context.Context, modelID string) (ModelMetadatum, error) {
	row := q.db.QueryRowContext(ctx, getModelMetadata, modelID)
	var i ModelMetadatum
	err := row.Scan(
		&i.ModelID,
		&i.NodeID,
		&i.StoragePath,
		&i.Alias,
		&i.Favourite,
		&i.Tags,
		&i.Description,
		&i.LoadCount,
		&i.LastLoaded,
		&i.TotalTokens,
		&i.Capabilities,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getModelMetadataCreatedAt = `-- name: GetModelMetadataCreatedAt :one
SELECT created_at FROM model_metadata WHERE model_id = ?
`

func (q *Queries) GetModelMetadataCreatedAt(ctx context.Context, modelID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getModelMetadataCreatedAt, modelID)
	var created_at int64
	err := row.Scan(&created_at)
	return created_at, err
}

const insertModelMetadata = `-- name: InsertModelMetadata :exec
INSERT INTO model_metadata (model_id, node_id, storage_path, alias, favourite, tags, description,
    load_count, last_loaded, total_tokens, capabilities, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertModelMetadataParams struct {
	ModelID      string         `json:"model_id"`
	NodeID       sql.NullString `json:"node_id"`
	StoragePath  sql.NullString `json:"storage_path"`
	Alias        sql.NullString `json:"alias"`
	Favourite    sql.NullInt64  `json:"favourite"`
	Tags         sql.NullString `json:"tags"`
	Description  sql.NullString `json:"description"`
	LoadCount    sql.NullInt64  `json:"load_count"`
	LastLoaded   sql.NullInt64  `json:"last_loaded"`
	TotalTokens  sql.NullInt64  `json:"total_tokens"`
	Capabilities sql.NullString `json:"capabilities"`
	CreatedAt    int64          `json:"created_at"`
	UpdatedAt    int64          `json:"updated_at"`
}

func (q *Queries) InsertModelMetadata(ctx context.Context, arg InsertModelMetadataParams) error {
	_, err := q.db.ExecContext(ctx, insertModelMetadata,
		arg.ModelID,
		arg.NodeID,
		arg.StoragePath,
		arg.Alias,
		arg.Favourite,
		arg.Tags,
		arg.Description,
		arg.LoadCount,
		arg.LastLoaded,
		arg.TotalTokens,
		arg.Capabilities,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const listModelMetadata = `-- name: ListModelMetadata :many
SELECT model_id, node_id, storage_path, alias, favourite, tags, description,
       load_count, last_loaded, total_tokens, capabilities, created_at, updated_at
FROM model_metadata
ORDER BY updated_at DESC
LIMIT ? OFFSET ?
`

type ListModelMetadataParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListModelMetadata(ctx context.Context, arg ListModelMetadataParams) ([]ModelMetadatum, error) {
	rows, err := q.db.QueryContext(ctx, listModelMetadata, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ModelMetadatum{}
	for rows.Next() {
		var i ModelMetadatum
		if err := rows.Scan(
			&i.ModelID,
			&i.NodeID,
			&i.StoragePath,
			&i.Alias,
			&i.Favourite,
			&i.Tags,
			&i.Description,
			&i.LoadCount,
			&i.LastLoaded,
			&i.TotalTokens,
			&i.Capabilities,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateModelMetadata = `-- name: UpdateModelMetadata :exec
UPDATE model_metadata
SET node_id = ?, storage_path = ?, alias = ?, favourite = ?, tags = ?, description = ?,
    load_count = ?, last_loaded = ?, total_tokens = ?, capabilities = ?, updated_at = ?
WHERE model_id = ?
`

type UpdateModelMetadataParams struct {
	NodeID       sql.NullString `json:"node_id"`
	StoragePath  sql.NullString `json:"storage_path"`
	Alias        sql.NullString `json:"alias"`
	Favourite    sql.NullInt64  `json:"favourite"`
	Tags         sql.NullString `json:"tags"`
	Description  sql.NullString `json:"description"`
	LoadCount    sql.NullInt64  `json:"load_count"`
	LastLoaded   sql.NullInt64  `json:"last_loaded"`
	TotalTokens  sql.NullInt64  `json:"total_tokens"`
	Capabilities sql.NullString `json:"capabilities"`
	UpdatedAt    int64          `json:"updated_at"`
	ModelID      string         `json:"model_id"`
}

func (q *Queries) UpdateModelMetadata(ctx context.Context, arg UpdateModelMetadataParams) error {
	_, err := q.db.ExecContext(ctx, updateModelMetadata,
		arg.NodeID,
		arg.StoragePath,
		arg.Alias,
		arg.Favourite,
		arg.Tags,
		arg.Description,
		arg.LoadCount,
		arg.LastLoaded,
		arg.TotalTokens,
		arg.Capabilities,
		arg.UpdatedAt,
		arg.ModelID,
	)
	return err
}
