// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: conversations.sql

package sqlcgen

import (
	"context"
)

const createConversation = `-- name: CreateConversation :exec
INSERT INTO conversations (id, model, title, system_prompt, message_count, created_at, updated_at, metadata)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateConversationParams struct {
	ID           string
	Model        string
	Title        *string
	SystemPrompt *string
	MessageCount *int64
	CreatedAt    int64
	UpdatedAt    int64
	Metadata     *string
}

func (q *Queries) CreateConversation(ctx context.Context, arg CreateConversationParams) error {
	_, err := q.db.ExecContext(ctx, createConversation,
		arg.ID,
		arg.Model,
		arg.Title,
		arg.SystemPrompt,
		arg.MessageCount,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Metadata,
	)
	return err
}

const deleteConversation = `-- name: DeleteConversation :exec
DELETE FROM conversations WHERE id = ?
`

func (q *Queries) DeleteConversation(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteConversation, id)
	return err
}

const getConversation = `-- name: GetConversation :one
SELECT id, model, title, system_prompt, message_count, created_at, updated_at, metadata FROM conversations WHERE id = ?
`

func (q *Queries) GetConversation(ctx context.Context, id string) (Conversation, error) {
	row := q.db.QueryRowContext(ctx, getConversation, id)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.Model,
		&i.Title,
		&i.SystemPrompt,
		&i.MessageCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Metadata,
	)
	return i, err
}

const listConversations = `-- name: ListConversations :many
SELECT id, model, title, system_prompt, message_count, created_at, updated_at, metadata FROM conversations ORDER BY updated_at DESC LIMIT ? OFFSET ?
`

type ListConversationsParams struct {
	Limit  int64
	Offset int64
}

func (q *Queries) ListConversations(ctx context.Context, arg ListConversationsParams) ([]Conversation, error) {
	rows, err := q.db.QueryContext(ctx, listConversations, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Conversation{}
	for rows.Next() {
		var i Conversation
		if err := rows.Scan(
			&i.ID,
			&i.Model,
			&i.Title,
			&i.SystemPrompt,
			&i.MessageCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateConversation = `-- name: UpdateConversation :exec
UPDATE conversations
SET model = ?, title = ?, system_prompt = ?, message_count = ?, updated_at = ?, metadata = ?
WHERE id = ?
`

type UpdateConversationParams struct {
	Model        string
	Title        *string
	SystemPrompt *string
	MessageCount *int64
	UpdatedAt    int64
	Metadata     *string
	ID           string
}

func (q *Queries) UpdateConversation(ctx context.Context, arg UpdateConversationParams) error {
	_, err := q.db.ExecContext(ctx, updateConversation,
		arg.Model,
		arg.Title,
		arg.SystemPrompt,
		arg.MessageCount,
		arg.UpdatedAt,
		arg.Metadata,
		arg.ID,
	)
	return err
}
