// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: download_tasks.sql

package sqlcgen

import (
	"context"
)

const createDownloadTask = `-- name: CreateDownloadTask :one
INSERT INTO download_tasks (
    id, url, path, file_name, state, downloaded_bytes, total_bytes,
    etag, range_supported, final_url, temp_file_name, parts_total, parts_completed,
    file_type, source_type, repo_id, error_message, retry_count, max_retries,
    created_at, started_at, finished_at
) VALUES (
    ?, ?, ?, ?, ?, ?, ?,
    ?, ?, ?, ?, ?, ?,
    ?, ?, ?, ?, ?, ?,
    ?, ?, ?
) RETURNING id, url, path, file_name, state, downloaded_bytes, total_bytes, etag, range_supported, final_url, temp_file_name, parts_total, parts_completed, file_type, source_type, repo_id, error_message, retry_count, max_retries, created_at, started_at, finished_at
`

type CreateDownloadTaskParams struct {
	ID              string
	Url             string
	Path            string
	FileName        string
	State           string
	DownloadedBytes *int64
	TotalBytes      *int64
	Etag            *string
	RangeSupported  *int64
	FinalUrl        *string
	TempFileName    *string
	PartsTotal      *int64
	PartsCompleted  *int64
	FileType        *string
	SourceType      *string
	RepoID          *string
	ErrorMessage    *string
	RetryCount      *int64
	MaxRetries      *int64
	CreatedAt       int64
	StartedAt       *int64
	FinishedAt      *int64
}

func (q *Queries) CreateDownloadTask(ctx context.Context, arg CreateDownloadTaskParams) (DownloadTask, error) {
	row := q.db.QueryRowContext(ctx, createDownloadTask,
		arg.ID,
		arg.Url,
		arg.Path,
		arg.FileName,
		arg.State,
		arg.DownloadedBytes,
		arg.TotalBytes,
		arg.Etag,
		arg.RangeSupported,
		arg.FinalUrl,
		arg.TempFileName,
		arg.PartsTotal,
		arg.PartsCompleted,
		arg.FileType,
		arg.SourceType,
		arg.RepoID,
		arg.ErrorMessage,
		arg.RetryCount,
		arg.MaxRetries,
		arg.CreatedAt,
		arg.StartedAt,
		arg.FinishedAt,
	)
	var i DownloadTask
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.Path,
		&i.FileName,
		&i.State,
		&i.DownloadedBytes,
		&i.TotalBytes,
		&i.Etag,
		&i.RangeSupported,
		&i.FinalUrl,
		&i.TempFileName,
		&i.PartsTotal,
		&i.PartsCompleted,
		&i.FileType,
		&i.SourceType,
		&i.RepoID,
		&i.ErrorMessage,
		&i.RetryCount,
		&i.MaxRetries,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const deleteDownloadTask = `-- name: DeleteDownloadTask :exec
DELETE FROM download_tasks WHERE id = ?
`

func (q *Queries) DeleteDownloadTask(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteDownloadTask, id)
	return err
}

const getDownloadTask = `-- name: GetDownloadTask :one
SELECT id, url, path, file_name, state, downloaded_bytes, total_bytes, etag, range_supported, final_url, temp_file_name, parts_total, parts_completed, file_type, source_type, repo_id, error_message, retry_count, max_retries, created_at, started_at, finished_at FROM download_tasks WHERE id = ?
`

func (q *Queries) GetDownloadTask(ctx context.Context, id string) (DownloadTask, error) {
	row := q.db.QueryRowContext(ctx, getDownloadTask, id)
	var i DownloadTask
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.Path,
		&i.FileName,
		&i.State,
		&i.DownloadedBytes,
		&i.TotalBytes,
		&i.Etag,
		&i.RangeSupported,
		&i.FinalUrl,
		&i.TempFileName,
		&i.PartsTotal,
		&i.PartsCompleted,
		&i.FileType,
		&i.SourceType,
		&i.RepoID,
		&i.ErrorMessage,
		&i.RetryCount,
		&i.MaxRetries,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const listActiveDownloadTasks = `-- name: ListActiveDownloadTasks :many
SELECT id, url, path, file_name, state, downloaded_bytes, total_bytes, etag, range_supported, final_url, temp_file_name, parts_total, parts_completed, file_type, source_type, repo_id, error_message, retry_count, max_retries, created_at, started_at, finished_at FROM download_tasks
WHERE state IN ('idle', 'preparing', 'downloading', 'merging', 'verifying', 'paused')
ORDER BY created_at DESC
`

func (q *Queries) ListActiveDownloadTasks(ctx context.Context) ([]DownloadTask, error) {
	rows, err := q.db.QueryContext(ctx, listActiveDownloadTasks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DownloadTask{}
	for rows.Next() {
		var i DownloadTask
		if err := rows.Scan(
			&i.ID,
			&i.Url,
			&i.Path,
			&i.FileName,
			&i.State,
			&i.DownloadedBytes,
			&i.TotalBytes,
			&i.Etag,
			&i.RangeSupported,
			&i.FinalUrl,
			&i.TempFileName,
			&i.PartsTotal,
			&i.PartsCompleted,
			&i.FileType,
			&i.SourceType,
			&i.RepoID,
			&i.ErrorMessage,
			&i.RetryCount,
			&i.MaxRetries,
			&i.CreatedAt,
			&i.StartedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDownloadTasks = `-- name: ListDownloadTasks :many
SELECT id, url, path, file_name, state, downloaded_bytes, total_bytes, etag, range_supported, final_url, temp_file_name, parts_total, parts_completed, file_type, source_type, repo_id, error_message, retry_count, max_retries, created_at, started_at, finished_at FROM download_tasks ORDER BY created_at DESC LIMIT ? OFFSET ?
`

type ListDownloadTasksParams struct {
	Limit  int64
	Offset int64
}

func (q *Queries) ListDownloadTasks(ctx context.Context, arg ListDownloadTasksParams) ([]DownloadTask, error) {
	rows, err := q.db.QueryContext(ctx, listDownloadTasks, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DownloadTask{}
	for rows.Next() {
		var i DownloadTask
		if err := rows.Scan(
			&i.ID,
			&i.Url,
			&i.Path,
			&i.FileName,
			&i.State,
			&i.DownloadedBytes,
			&i.TotalBytes,
			&i.Etag,
			&i.RangeSupported,
			&i.FinalUrl,
			&i.TempFileName,
			&i.PartsTotal,
			&i.PartsCompleted,
			&i.FileType,
			&i.SourceType,
			&i.RepoID,
			&i.ErrorMessage,
			&i.RetryCount,
			&i.MaxRetries,
			&i.CreatedAt,
			&i.StartedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDownloadTask = `-- name: UpdateDownloadTask :one
UPDATE download_tasks
SET url = ?, path = ?, file_name = ?, state = ?, downloaded_bytes = ?, total_bytes = ?,
    etag = ?, range_supported = ?, final_url = ?, temp_file_name = ?,
    parts_total = ?, parts_completed = ?, file_type = ?, source_type = ?,
    repo_id = ?, error_message = ?, retry_count = ?, max_retries = ?,
    started_at = ?, finished_at = ?
WHERE id = ?
RETURNING id, url, path, file_name, state, downloaded_bytes, total_bytes, etag, range_supported, final_url, temp_file_name, parts_total, parts_completed, file_type, source_type, repo_id, error_message, retry_count, max_retries, created_at, started_at, finished_at
`

type UpdateDownloadTaskParams struct {
	Url             string
	Path            string
	FileName        string
	State           string
	DownloadedBytes *int64
	TotalBytes      *int64
	Etag            *string
	RangeSupported  *int64
	FinalUrl        *string
	TempFileName    *string
	PartsTotal      *int64
	PartsCompleted  *int64
	FileType        *string
	SourceType      *string
	RepoID          *string
	ErrorMessage    *string
	RetryCount      *int64
	MaxRetries      *int64
	StartedAt       *int64
	FinishedAt      *int64
	ID              string
}

func (q *Queries) UpdateDownloadTask(ctx context.Context, arg UpdateDownloadTaskParams) (DownloadTask, error) {
	row := q.db.QueryRowContext(ctx, updateDownloadTask,
		arg.Url,
		arg.Path,
		arg.FileName,
		arg.State,
		arg.DownloadedBytes,
		arg.TotalBytes,
		arg.Etag,
		arg.RangeSupported,
		arg.FinalUrl,
		arg.TempFileName,
		arg.PartsTotal,
		arg.PartsCompleted,
		arg.FileType,
		arg.SourceType,
		arg.RepoID,
		arg.ErrorMessage,
		arg.RetryCount,
		arg.MaxRetries,
		arg.StartedAt,
		arg.FinishedAt,
		arg.ID,
	)
	var i DownloadTask
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.Path,
		&i.FileName,
		&i.State,
		&i.DownloadedBytes,
		&i.TotalBytes,
		&i.Etag,
		&i.RangeSupported,
		&i.FinalUrl,
		&i.TempFileName,
		&i.PartsTotal,
		&i.PartsCompleted,
		&i.FileType,
		&i.SourceType,
		&i.RepoID,
		&i.ErrorMessage,
		&i.RetryCount,
		&i.MaxRetries,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}
