// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: messages.sql

package sqlcgen

import (
	"context"
)

const createMessage = `-- name: CreateMessage :exec
INSERT INTO messages (id, conversation_id, role, content, name, token_count, created_at, metadata)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateMessageParams struct {
	ID             string
	ConversationID string
	Role           string
	Content        string
	Name           *string
	TokenCount     *int64
	CreatedAt      int64
	Metadata       *string
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) error {
	_, err := q.db.ExecContext(ctx, createMessage,
		arg.ID,
		arg.ConversationID,
		arg.Role,
		arg.Content,
		arg.Name,
		arg.TokenCount,
		arg.CreatedAt,
		arg.Metadata,
	)
	return err
}

const deleteMessages = `-- name: DeleteMessages :exec
DELETE FROM messages WHERE conversation_id = ?
`

func (q *Queries) DeleteMessages(ctx context.Context, conversationID string) error {
	_, err := q.db.ExecContext(ctx, deleteMessages, conversationID)
	return err
}

const getMessages = `-- name: GetMessages :many
SELECT id, conversation_id, role, content, name, token_count, created_at, metadata FROM messages
WHERE conversation_id = ?
ORDER BY created_at ASC
LIMIT ? OFFSET ?
`

type GetMessagesParams struct {
	ConversationID string
	Limit          int64
	Offset         int64
}

func (q *Queries) GetMessages(ctx context.Context, arg GetMessagesParams) ([]Message, error) {
	rows, err := q.db.QueryContext(ctx, getMessages, arg.ConversationID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.Role,
			&i.Content,
			&i.Name,
			&i.TokenCount,
			&i.CreatedAt,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const incrementConversationMessageCount = `-- name: IncrementConversationMessageCount :exec
UPDATE conversations SET message_count = message_count + 1, updated_at = ? WHERE id = ?
`

type IncrementConversationMessageCountParams struct {
	UpdatedAt int64
	ID        string
}

func (q *Queries) IncrementConversationMessageCount(ctx context.Context, arg IncrementConversationMessageCountParams) error {
	_, err := q.db.ExecContext(ctx, incrementConversationMessageCount, arg.UpdatedAt, arg.ID)
	return err
}

const resetConversationMessageCount = `-- name: ResetConversationMessageCount :exec
UPDATE conversations SET message_count = 0, updated_at = ? WHERE id = ?
`

type ResetConversationMessageCountParams struct {
	UpdatedAt int64
	ID        string
}

func (q *Queries) ResetConversationMessageCount(ctx context.Context, arg ResetConversationMessageCountParams) error {
	_, err := q.db.ExecContext(ctx, resetConversationMessageCount, arg.UpdatedAt, arg.ID)
	return err
}
