// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

type Benchmark struct {
	ID         string
	ModelID    string
	ModelName  string
	Status     string
	Command    *string
	Config     *string
	Metrics    *string
	Error      *string
	CreatedAt  int64
	StartedAt  *int64
	FinishedAt *int64
}

type BenchmarkConfig struct {
	Name         string
	ModelID      string
	ModelName    string
	LlamacppPath string
	Devices      *string
	Params       *string
	CreatedAt    int64
}

type Conversation struct {
	ID           string
	Model        string
	Title        *string
	SystemPrompt *string
	MessageCount *int64
	CreatedAt    int64
	UpdatedAt    int64
	Metadata     *string
}

type DownloadTask struct {
	ID              string
	Url             string
	Path            string
	FileName        string
	State           string
	DownloadedBytes *int64
	TotalBytes      *int64
	Etag            *string
	RangeSupported  *int64
	FinalUrl        *string
	TempFileName    *string
	PartsTotal      *int64
	PartsCompleted  *int64
	FileType        *string
	SourceType      *string
	RepoID          *string
	ErrorMessage    *string
	RetryCount      *int64
	MaxRetries      *int64
	CreatedAt       int64
	StartedAt       *int64
	FinishedAt      *int64
}

type Message struct {
	ID             string
	ConversationID string
	Role           string
	Content        string
	Name           *string
	TokenCount     *int64
	CreatedAt      int64
	Metadata       *string
}

type ModelLoadConfig struct {
	ID        string
	NodeID    string
	ModelID   string
	ModelName string
	Config    string
	CreatedAt int64
	UpdatedAt int64
	Name      string
}

type ModelMetadatum struct {
	ModelID      string
	NodeID       *string
	StoragePath  *string
	Alias        *string
	Favourite    *int64
	Tags         *string
	Description  *string
	LoadCount    *int64
	LastLoaded   *int64
	TotalTokens  *int64
	Capabilities *string
	CreatedAt    int64
	UpdatedAt    int64
}

type TtsHistory struct {
	ID        string
	Model     string
	InputText string
	AudioPath string
	Format    string
	Duration  *float64
	Favourite *int64
	Params    *string
	CreatedAt int64
}
