// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: download_tasks.sql

package mysqldb

import (
	"context"
	"database/sql"
)

const createDownloadTask = `-- name: CreateDownloadTask :exec
INSERT INTO download_tasks (id, url, path, file_name, state, downloaded_bytes, total_bytes,
    etag, range_supported, final_url, temp_file_name, parts_total, parts_completed,
    file_type, source_type, repo_id, error_message, retry_count, max_retries,
    created_at, started_at, finished_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateDownloadTaskParams struct {
	ID              string         `json:"id"`
	Url             string         `json:"url"`
	Path            string         `json:"path"`
	FileName        string         `json:"file_name"`
	State           string         `json:"state"`
	DownloadedBytes sql.NullInt64  `json:"downloaded_bytes"`
	TotalBytes      sql.NullInt64  `json:"total_bytes"`
	Etag            sql.NullString `json:"etag"`
	RangeSupported  sql.NullInt16  `json:"range_supported"`
	FinalUrl        sql.NullString `json:"final_url"`
	TempFileName    sql.NullString `json:"temp_file_name"`
	PartsTotal      sql.NullInt32  `json:"parts_total"`
	PartsCompleted  sql.NullInt32  `json:"parts_completed"`
	FileType        sql.NullString `json:"file_type"`
	SourceType      sql.NullString `json:"source_type"`
	RepoID          sql.NullString `json:"repo_id"`
	ErrorMessage    sql.NullString `json:"error_message"`
	RetryCount      sql.NullInt32  `json:"retry_count"`
	MaxRetries      sql.NullInt32  `json:"max_retries"`
	CreatedAt       int64          `json:"created_at"`
	StartedAt       sql.NullInt64  `json:"started_at"`
	FinishedAt      sql.NullInt64  `json:"finished_at"`
}

func (q *Queries) CreateDownloadTask(ctx context.Context, arg CreateDownloadTaskParams) error {
	_, err := q.db.ExecContext(ctx, createDownloadTask,
		arg.ID,
		arg.Url,
		arg.Path,
		arg.FileName,
		arg.State,
		arg.DownloadedBytes,
		arg.TotalBytes,
		arg.Etag,
		arg.RangeSupported,
		arg.FinalUrl,
		arg.TempFileName,
		arg.PartsTotal,
		arg.PartsCompleted,
		arg.FileType,
		arg.SourceType,
		arg.RepoID,
		arg.ErrorMessage,
		arg.RetryCount,
		arg.MaxRetries,
		arg.CreatedAt,
		arg.StartedAt,
		arg.FinishedAt,
	)
	return err
}

const deleteDownloadTask = `-- name: DeleteDownloadTask :exec
DELETE FROM download_tasks WHERE id = ?
`

func (q *Queries) DeleteDownloadTask(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteDownloadTask, id)
	return err
}

const getDownloadTask = `-- name: GetDownloadTask :one
SELECT id, url, path, file_name, state, downloaded_bytes, total_bytes,
    etag, range_supported, final_url, temp_file_name, parts_total, parts_completed,
    file_type, source_type, repo_id, error_message, retry_count, max_retries,
    created_at, started_at, finished_at
FROM download_tasks WHERE id = ?
`

func (q *Queries) GetDownloadTask(ctx context.Context, id string) (DownloadTask, error) {
	row := q.db.QueryRowContext(ctx, getDownloadTask, id)
	var i DownloadTask
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.Path,
		&i.FileName,
		&i.State,
		&i.DownloadedBytes,
		&i.TotalBytes,
		&i.Etag,
		&i.RangeSupported,
		&i.FinalUrl,
		&i.TempFileName,
		&i.PartsTotal,
		&i.PartsCompleted,
		&i.FileType,
		&i.SourceType,
		&i.RepoID,
		&i.ErrorMessage,
		&i.RetryCount,
		&i.MaxRetries,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const listActiveDownloadTasks = `-- name: ListActiveDownloadTasks :many
SELECT id, url, path, file_name, state, downloaded_bytes, total_bytes,
    etag, range_supported, final_url, temp_file_name, parts_total, parts_completed,
    file_type, source_type, repo_id, error_message, retry_count, max_retries,
    created_at, started_at, finished_at
FROM download_tasks
WHERE state IN ('idle', 'preparing', 'downloading', 'merging', 'verifying', 'paused')
ORDER BY created_at DESC
`

func (q *Queries) ListActiveDownloadTasks(ctx context.Context) ([]DownloadTask, error) {
	rows, err := q.db.QueryContext(ctx, listActiveDownloadTasks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DownloadTask{}
	for rows.Next() {
		var i DownloadTask
		if err := rows.Scan(
			&i.ID,
			&i.Url,
			&i.Path,
			&i.FileName,
			&i.State,
			&i.DownloadedBytes,
			&i.TotalBytes,
			&i.Etag,
			&i.RangeSupported,
			&i.FinalUrl,
			&i.TempFileName,
			&i.PartsTotal,
			&i.PartsCompleted,
			&i.FileType,
			&i.SourceType,
			&i.RepoID,
			&i.ErrorMessage,
			&i.RetryCount,
			&i.MaxRetries,
			&i.CreatedAt,
			&i.StartedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDownloadTasks = `-- name: ListDownloadTasks :many
SELECT id, url, path, file_name, state, downloaded_bytes, total_bytes,
    etag, range_supported, final_url, temp_file_name, parts_total, parts_completed,
    file_type, source_type, repo_id, error_message, retry_count, max_retries,
    created_at, started_at, finished_at
FROM download_tasks
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type ListDownloadTasksParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListDownloadTasks(ctx context.Context, arg ListDownloadTasksParams) ([]DownloadTask, error) {
	rows, err := q.db.QueryContext(ctx, listDownloadTasks, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DownloadTask{}
	for rows.Next() {
		var i DownloadTask
		if err := rows.Scan(
			&i.ID,
			&i.Url,
			&i.Path,
			&i.FileName,
			&i.State,
			&i.DownloadedBytes,
			&i.TotalBytes,
			&i.Etag,
			&i.RangeSupported,
			&i.FinalUrl,
			&i.TempFileName,
			&i.PartsTotal,
			&i.PartsCompleted,
			&i.FileType,
			&i.SourceType,
			&i.RepoID,
			&i.ErrorMessage,
			&i.RetryCount,
			&i.MaxRetries,
			&i.CreatedAt,
			&i.StartedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDownloadTask = `-- name: UpdateDownloadTask :exec
UPDATE download_tasks
SET url = ?, path = ?, file_name = ?, state = ?, downloaded_bytes = ?, total_bytes = ?,
    etag = ?, range_supported = ?, final_url = ?, temp_file_name = ?,
    parts_total = ?, parts_completed = ?, file_type = ?, source_type = ?,
    repo_id = ?, error_message = ?, retry_count = ?, max_retries = ?,
    started_at = ?, finished_at = ?
WHERE id = ?
`

type UpdateDownloadTaskParams struct {
	Url             string         `json:"url"`
	Path            string         `json:"path"`
	FileName        string         `json:"file_name"`
	State           string         `json:"state"`
	DownloadedBytes sql.NullInt64  `json:"downloaded_bytes"`
	TotalBytes      sql.NullInt64  `json:"total_bytes"`
	Etag            sql.NullString `json:"etag"`
	RangeSupported  sql.NullInt16  `json:"range_supported"`
	FinalUrl        sql.NullString `json:"final_url"`
	TempFileName    sql.NullString `json:"temp_file_name"`
	PartsTotal      sql.NullInt32  `json:"parts_total"`
	PartsCompleted  sql.NullInt32  `json:"parts_completed"`
	FileType        sql.NullString `json:"file_type"`
	SourceType      sql.NullString `json:"source_type"`
	RepoID          sql.NullString `json:"repo_id"`
	ErrorMessage    sql.NullString `json:"error_message"`
	RetryCount      sql.NullInt32  `json:"retry_count"`
	MaxRetries      sql.NullInt32  `json:"max_retries"`
	StartedAt       sql.NullInt64  `json:"started_at"`
	FinishedAt      sql.NullInt64  `json:"finished_at"`
	ID              string         `json:"id"`
}

func (q *Queries) UpdateDownloadTask(ctx context.Context, arg UpdateDownloadTaskParams) error {
	_, err := q.db.ExecContext(ctx, updateDownloadTask,
		arg.Url,
		arg.Path,
		arg.FileName,
		arg.State,
		arg.DownloadedBytes,
		arg.TotalBytes,
		arg.Etag,
		arg.RangeSupported,
		arg.FinalUrl,
		arg.TempFileName,
		arg.PartsTotal,
		arg.PartsCompleted,
		arg.FileType,
		arg.SourceType,
		arg.RepoID,
		arg.ErrorMessage,
		arg.RetryCount,
		arg.MaxRetries,
		arg.StartedAt,
		arg.FinishedAt,
		arg.ID,
	)
	return err
}
