// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: messages.sql

package mysqldb

import (
	"context"
	"database/sql"
)

const createMessage = `-- name: CreateMessage :exec
INSERT INTO messages (id, conversation_id, role, content, name, token_count, created_at, metadata)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateMessageParams struct {
	ID             string         `json:"id"`
	ConversationID string         `json:"conversation_id"`
	Role           string         `json:"role"`
	Content        string         `json:"content"`
	Name           sql.NullString `json:"name"`
	TokenCount     sql.NullInt32  `json:"token_count"`
	CreatedAt      int64          `json:"created_at"`
	Metadata       sql.NullString `json:"metadata"`
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) error {
	_, err := q.db.ExecContext(ctx, createMessage,
		arg.ID,
		arg.ConversationID,
		arg.Role,
		arg.Content,
		arg.Name,
		arg.TokenCount,
		arg.CreatedAt,
		arg.Metadata,
	)
	return err
}

const deleteMessages = `-- name: DeleteMessages :exec
DELETE FROM messages WHERE conversation_id = ?
`

func (q *Queries) DeleteMessages(ctx context.Context, conversationID string) error {
	_, err := q.db.ExecContext(ctx, deleteMessages, conversationID)
	return err
}

const getMessages = `-- name: GetMessages :many
SELECT id, conversation_id, role, content, name, token_count, created_at, metadata
FROM messages
WHERE conversation_id = ?
ORDER BY created_at ASC
LIMIT ? OFFSET ?
`

type GetMessagesParams struct {
	ConversationID string `json:"conversation_id"`
	Limit          int32  `json:"limit"`
	Offset         int32  `json:"offset"`
}

func (q *Queries) GetMessages(ctx context.Context, arg GetMessagesParams) ([]Message, error) {
	rows, err := q.db.QueryContext(ctx, getMessages, arg.ConversationID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.Role,
			&i.Content,
			&i.Name,
			&i.TokenCount,
			&i.CreatedAt,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
