// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: model_load_configs.sql

package mysqldb

import (
	"context"
)

const deleteModelLoadConfig = `-- name: DeleteModelLoadConfig :exec
DELETE FROM model_load_configs WHERE node_id = ? AND model_id = ? AND name = ''
`

type DeleteModelLoadConfigParams struct {
	NodeID  string `json:"node_id"`
	ModelID string `json:"model_id"`
}

func (q *Queries) DeleteModelLoadConfig(ctx context.Context, arg DeleteModelLoadConfigParams) error {
	_, err := q.db.ExecContext(ctx, deleteModelLoadConfig, arg.NodeID, arg.ModelID)
	return err
}

const deleteNamedModelLoadConfig = `-- name: DeleteNamedModelLoadConfig :exec
DELETE FROM model_load_configs WHERE node_id = ? AND model_id = ? AND name = ?
`

type DeleteNamedModelLoadConfigParams struct {
	NodeID  string `json:"node_id"`
	ModelID string `json:"model_id"`
	Name    string `json:"name"`
}

func (q *Queries) DeleteNamedModelLoadConfig(ctx context.Context, arg DeleteNamedModelLoadConfigParams) error {
	_, err := q.db.ExecContext(ctx, deleteNamedModelLoadConfig, arg.NodeID, arg.ModelID, arg.Name)
	return err
}

const getModelLoadConfig = `-- name: GetModelLoadConfig :one
SELECT id, node_id, model_id, model_name, config, created_at, updated_at, name
FROM model_load_configs
WHERE node_id = ? AND model_id = ? AND name = ''
`

type GetModelLoadConfigParams struct {
	NodeID  string `json:"node_id"`
	ModelID string `json:"model_id"`
}

func (q *Queries) GetModelLoadConfig(ctx context.Context, arg GetModelLoadConfigParams) (ModelLoadConfig, error) {
	row := q.db.QueryRowContext(ctx, getModelLoadConfig, arg.NodeID, arg.ModelID)
	var i ModelLoadConfig
	err := row.Scan(
		&i.ID,
		&i.NodeID,
		&i.ModelID,
		&i.ModelName,
		&i.Config,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
	)
	return i, err
}

const listModelLoadConfigs = `-- name: ListModelLoadConfigs :many
SELECT id, node_id, model_id, model_name, config, created_at, updated_at, name
FROM model_load_configs
WHERE node_id = ? AND model_id = ?
ORDER BY name
`

type ListModelLoadConfigsParams struct {
	NodeID  string `json:"node_id"`
	ModelID string `json:"model_id"`
}

func (q *Queries) ListModelLoadConfigs(ctx context.Context, arg ListModelLoadConfigsParams) ([]ModelLoadConfig, error) {
	rows, err := q.db.QueryContext(ctx, listModelLoadConfigs, arg.NodeID, arg.ModelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ModelLoadConfig{}
	for rows.Next() {
		var i ModelLoadConfig
		if err := rows.Scan(
			&i.ID,
			&i.NodeID,
			&i.ModelID,
			&i.ModelName,
			&i.Config,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertModelLoadConfig = `-- name: UpsertModelLoadConfig :exec
INSERT INTO model_load_configs (id, node_id, model_id, model_name, config, created_at, updated_at, name)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
ON DUPLICATE KEY UPDATE
    config = VALUES(config),
    model_name = VALUES(model_name),
    updated_at = VALUES(updated_at)
`

type UpsertModelLoadConfigParams struct {
	ID        string `json:"id"`
	NodeID    string `json:"node_id"`
	ModelID   string `json:"model_id"`
	ModelName string `json:"model_name"`
	Config    string `json:"config"`
	CreatedAt int64  `json:"created_at"`
	UpdatedAt int64  `json:"updated_at"`
	Name      string `json:"name"`
}

func (q *Queries) UpsertModelLoadConfig(ctx context.Context, arg UpsertModelLoadConfigParams) error {
	_, err := q.db.ExecContext(ctx, upsertModelLoadConfig,
		arg.ID,
		arg.NodeID,
		arg.ModelID,
		arg.ModelName,
		arg.Config,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Name,
	)
	return err
}
