// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package mysqldb

import (
	"database/sql"
)

type Benchmark struct {
	ID         string         `json:"id"`
	ModelID    string         `json:"model_id"`
	ModelName  string         `json:"model_name"`
	Status     string         `json:"status"`
	Command    sql.NullString `json:"command"`
	Config     sql.NullString `json:"config"`
	Metrics    sql.NullString `json:"metrics"`
	Error      sql.NullString `json:"error"`
	CreatedAt  int64          `json:"created_at"`
	StartedAt  sql.NullInt64  `json:"started_at"`
	FinishedAt sql.NullInt64  `json:"finished_at"`
}

type BenchmarkConfig struct {
	Name         string         `json:"name"`
	ModelID      string         `json:"model_id"`
	ModelName    string         `json:"model_name"`
	LlamacppPath string         `json:"llamacpp_path"`
	Devices      sql.NullString `json:"devices"`
	Params       sql.NullString `json:"params"`
	CreatedAt    int64          `json:"created_at"`
}

type Conversation struct {
	ID           string         `json:"id"`
	Model        string         `json:"model"`
	Title        sql.NullString `json:"title"`
	SystemPrompt sql.NullString `json:"system_prompt"`
	MessageCount sql.NullInt32  `json:"message_count"`
	CreatedAt    int64          `json:"created_at"`
	UpdatedAt    int64          `json:"updated_at"`
	Metadata     sql.NullString `json:"metadata"`
}

type DownloadTask struct {
	ID              string         `json:"id"`
	Url             string         `json:"url"`
	Path            string         `json:"path"`
	FileName        string         `json:"file_name"`
	State           string         `json:"state"`
	DownloadedBytes sql.NullInt64  `json:"downloaded_bytes"`
	TotalBytes      sql.NullInt64  `json:"total_bytes"`
	Etag            sql.NullString `json:"etag"`
	RangeSupported  sql.NullInt16  `json:"range_supported"`
	FinalUrl        sql.NullString `json:"final_url"`
	TempFileName    sql.NullString `json:"temp_file_name"`
	PartsTotal      sql.NullInt32  `json:"parts_total"`
	PartsCompleted  sql.NullInt32  `json:"parts_completed"`
	FileType        sql.NullString `json:"file_type"`
	SourceType      sql.NullString `json:"source_type"`
	RepoID          sql.NullString `json:"repo_id"`
	ErrorMessage    sql.NullString `json:"error_message"`
	RetryCount      sql.NullInt32  `json:"retry_count"`
	MaxRetries      sql.NullInt32  `json:"max_retries"`
	CreatedAt       int64          `json:"created_at"`
	StartedAt       sql.NullInt64  `json:"started_at"`
	FinishedAt      sql.NullInt64  `json:"finished_at"`
}

type LaunchProfile struct {
	ID             string         `json:"id"`
	Name           string         `json:"name"`
	BackendType    string         `json:"backend_type"`
	InstallationID sql.NullString `json:"installation_id"`
	ModelScope     sql.NullString `json:"model_scope"`
	Params         string         `json:"params"`
	Env            sql.NullString `json:"env"`
	ExtraArgs      sql.NullString `json:"extra_args"`
	CreatedAt      int64          `json:"created_at"`
	UpdatedAt      int64          `json:"updated_at"`
}

type Message struct {
	ID             string         `json:"id"`
	ConversationID string         `json:"conversation_id"`
	Role           string         `json:"role"`
	Content        string         `json:"content"`
	Name           sql.NullString `json:"name"`
	TokenCount     sql.NullInt32  `json:"token_count"`
	CreatedAt      int64          `json:"created_at"`
	Metadata       sql.NullString `json:"metadata"`
}

type ModelLoadConfig struct {
	ID        string `json:"id"`
	NodeID    string `json:"node_id"`
	ModelID   string `json:"model_id"`
	ModelName string `json:"model_name"`
	Config    string `json:"config"`
	CreatedAt int64  `json:"created_at"`
	UpdatedAt int64  `json:"updated_at"`
	Name      string `json:"name"`
}

type ModelMetadatum struct {
	ModelID      string         `json:"model_id"`
	NodeID       sql.NullString `json:"node_id"`
	StoragePath  sql.NullString `json:"storage_path"`
	Alias        sql.NullString `json:"alias"`
	Favourite    sql.NullInt16  `json:"favourite"`
	Tags         sql.NullString `json:"tags"`
	Description  sql.NullString `json:"description"`
	LoadCount    sql.NullInt32  `json:"load_count"`
	LastLoaded   sql.NullInt64  `json:"last_loaded"`
	TotalTokens  sql.NullInt64  `json:"total_tokens"`
	Capabilities sql.NullString `json:"capabilities"`
	CreatedAt    int64          `json:"created_at"`
	UpdatedAt    int64          `json:"updated_at"`
}

type TtsHistory struct {
	ID        string          `json:"id"`
	Model     string          `json:"model"`
	InputText string          `json:"input_text"`
	AudioPath string          `json:"audio_path"`
	Format    string          `json:"format"`
	Duration  sql.NullFloat64 `json:"duration"`
	Favourite sql.NullInt16   `json:"favourite"`
	Params    sql.NullString  `json:"params"`
	CreatedAt int64           `json:"created_at"`
}
