// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tts_history.sql

package mysqldb

import (
	"context"
	"database/sql"
)

const createTTSHistory = `-- name: CreateTTSHistory :exec
INSERT INTO tts_history (id, model, input_text, audio_path, format, duration, favourite, params, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateTTSHistoryParams struct {
	ID        string          `json:"id"`
	Model     string          `json:"model"`
	InputText string          `json:"input_text"`
	AudioPath string          `json:"audio_path"`
	Format    string          `json:"format"`
	Duration  sql.NullFloat64 `json:"duration"`
	Favourite sql.NullInt16   `json:"favourite"`
	Params    sql.NullString  `json:"params"`
	CreatedAt int64           `json:"created_at"`
}

func (q *Queries) CreateTTSHistory(ctx context.Context, arg CreateTTSHistoryParams) error {
	_, err := q.db.ExecContext(ctx, createTTSHistory,
		arg.ID,
		arg.Model,
		arg.InputText,
		arg.AudioPath,
		arg.Format,
		arg.Duration,
		arg.Favourite,
		arg.Params,
		arg.CreatedAt,
	)
	return err
}

const deleteTTSHistory = `-- name: DeleteTTSHistory :exec
DELETE FROM tts_history WHERE id = ?
`

func (q *Queries) DeleteTTSHistory(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteTTSHistory, id)
	return err
}

const getTTSHistory = `-- name: GetTTSHistory :one
SELECT id, model, input_text, audio_path, format, duration, favourite, params, created_at
FROM tts_history WHERE id = ?
`

func (q *Queries) GetTTSHistory(ctx context.Context, id string) (TtsHistory, error) {
	row := q.db.QueryRowContext(ctx, getTTSHistory, id)
	var i TtsHistory
	err := row.Scan(
		&i.ID,
		&i.Model,
		&i.InputText,
		&i.AudioPath,
		&i.Format,
		&i.Duration,
		&i.Favourite,
		&i.Params,
		&i.CreatedAt,
	)
	return i, err
}

const listTTSHistory = `-- name: ListTTSHistory :many
SELECT id, model, input_text, audio_path, format, duration, favourite, params, created_at
FROM tts_history
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type ListTTSHistoryParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListTTSHistory(ctx context.Context, arg ListTTSHistoryParams) ([]TtsHistory, error) {
	rows, err := q.db.QueryContext(ctx, listTTSHistory, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TtsHistory{}
	for rows.Next() {
		var i TtsHistory
		if err := rows.Scan(
			&i.ID,
			&i.Model,
			&i.InputText,
			&i.AudioPath,
			&i.Format,
			&i.Duration,
			&i.Favourite,
			&i.Params,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTTSHistoryFavourite = `-- name: ListTTSHistoryFavourite :many
SELECT id, model, input_text, audio_path, format, duration, favourite, params, created_at
FROM tts_history
WHERE favourite = 1
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type ListTTSHistoryFavouriteParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListTTSHistoryFavourite(ctx context.Context, arg ListTTSHistoryFavouriteParams) ([]TtsHistory, error) {
	rows, err := q.db.QueryContext(ctx, listTTSHistoryFavourite, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TtsHistory{}
	for rows.Next() {
		var i TtsHistory
		if err := rows.Scan(
			&i.ID,
			&i.Model,
			&i.InputText,
			&i.AudioPath,
			&i.Format,
			&i.Duration,
			&i.Favourite,
			&i.Params,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTTSHistoryFavourite = `-- name: UpdateTTSHistoryFavourite :exec
UPDATE tts_history SET favourite = ? WHERE id = ?
`

type UpdateTTSHistoryFavouriteParams struct {
	Favourite sql.NullInt16 `json:"favourite"`
	ID        string        `json:"id"`
}

func (q *Queries) UpdateTTSHistoryFavourite(ctx context.Context, arg UpdateTTSHistoryFavouriteParams) error {
	_, err := q.db.ExecContext(ctx, updateTTSHistoryFavourite, arg.Favourite, arg.ID)
	return err
}
